### PR TITLE
windows: enable virtual terminal processing, fixes #169

### LINKED ISSUE #169: Colors not working in Powershell env
Using the Cluster API CLI clusterctl prints the output with color on linux and mac environments, but the same does not work for Windows PowerShell and cmd. The output includes the Raw ANSI codes instead making it unreadable. The current workaround is to set the `NO_COLOR` env variable to turn off color completely, resulting in a readable, but colorless output.

 Is there a way to configure the library to get the correctly colored output on Windows environments? 

Related issue: https://github.com/kubernetes-sigs/cluster-api/issues/7381

### PR DESCRIPTION
**Pull request by martinlindhe**
This PR supersedes #173 because I accidentally deleted local fork.

It is the same PR except x/sys bumped to 0.5.0.

### CODE REVIEW

File: color_windows.go [hunk 1]
```diff
@@ -0,0 +1,18 @@
+package color
+
+import (
+	"os"
+
+	"golang.org/x/sys/windows"
+)
+
+func init() {
+	// Opt-in for ansi color support for current process.
```
Comment (pellared) [inline color_windows.go:10]: Can we use `NO_COLOR` env var and `NoColor = true` global variable to opt-out?

https://github.com/fatih/color/pull/173#discussion_r1116624911

File: color_windows.go [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+	// https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#output-sequences
+	var outMode uint32
+	out := windows.Handle(os.Stdout.Fd())
+	if err := windows.GetConsoleMode(out, &outMode); err == nil {
+		outMode |= windows.ENABLE_PROCESSED_OUTPUT | windows.ENABLE_VIRTUAL_TERMINAL_PROCESSING
+		_ = windows.SetConsoleMode(out, outMode)
+	}
```
Comment (pellared) [inline color_windows.go:17]: Indent Error Flow

```suggestion
	if err := windows.GetConsoleMode(out, &outMode); err != nil {
		return
	}
	outMode |= windows.ENABLE_PROCESSED_OUTPUT | windows.ENABLE_VIRTUAL_TERMINAL_PROCESSING
	_ = windows.SetConsoleMode(out, outMode)
```

reference: https://github.com/golang/go/wiki/CodeReviewComments#indent-error-flow

**Comment by fatih** [comment]
Thank you @martinlindhe

File: color_windows.go (hunk 1 above)
Comment (fatih) [reply color_windows.go:10]: the `NO_COLOR` env already changes the `NoColor` value. So we can just check for the `NoColor` variable and it'll cover everything.

Comment (pellared) [reply color_windows.go:10]: So I guess it is just a matter of adding

```golang
if NoColor {
  return
}
```

right? 😉

Comment (fatih) [reply color_windows.go:10]: The problem though is, it wouldn't work as expected. Imagine this situation:

1. You import color and enable `NO_COLOR`.
2. The `init()` is called, it check's `NoColor`, if it's false it will not set the configuration
3. After a while though, you set `NoColor = false`.
4. It still doesn't work, because `init()` will not run anymore. So we need a separate enviornment variable. `NoColor` is  working fine as it's now, but it wouldn't work opt-out.

File: color_windows.go (hunk 2 above)
Comment (martinlindhe) [reply color_windows.go:17]: @pellared I sent yet another PR for your last 2 comments. See #187

File: color_windows.go (hunk 1 above)
Comment (martinlindhe) [reply color_windows.go:10]: Regarding #2. init() is run after all var () blocks, so NoColor would be set before init() is called.
