### PR TITLE
Properly handle single arg calls to helper funcs

### LINKED ISSUE #39: Properly handle single arg calls to helper funcs
When calling `Red("cat%dog")` or `RedString("cat%dog")` without additional args, the string is interpreted as a format.  The result is `cat%!d(MISSING)dog`.  This is unexpected behavior.  Or as @davecheney said, "Wow, what an API footgun."

See davecheney/httpstat/pull/70

### PR DESCRIPTION
**Pull request by moorereason**
Fixes #39

### CODE REVIEW

File: color.go [hunk 1]
```diff
@@ -345,6 +345,11 @@ func Cyan(format string, a ...interface{}) { printColor(format, FgCyan, a...) }
 func White(format string, a ...interface{}) { printColor(format, FgWhite, a...) }
 
 func printColor(format string, p Attribute, a ...interface{}) {
+	if len(a) == 0 {
+		a = append(a, format)
+		format = "%s"
+	}
```
Comment (fatih) [inline color.go]: I assume this fixes the cases for `color.White`, `color.Cyan`, etc.. However there are no tests for these. Can you please also add those ?

Comment (moorereason) [inline color.go]: Pushed another commit to add visual tests.

**Comment by fatih** [comment]
Thanks @moorereason 👍
